# Generated by Django 4.2.2 on 2024-11-06 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_customuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Введите имя пользователя",
                max_length=50,
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
