# Generated by Django 5.1.2 on 2024-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержимое продукта",
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Добавьте изображение продукта",
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("sign_publication", models.BooleanField(default=True)),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счётчик просмотров",
                    ),
                ),
            ],
        ),
    ]
