# Generated by Django 5.1.2 on 2024-10-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="view_counter",
            new_name="view_count",
        ),
    ]
