# Generated by Django 5.1.2 on 2024-10-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_view_counter_blog_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
