# Generated by Django 5.1.2 on 2024-10-14 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счётчик просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now,
                help_text="Добавьте изображение продукта",
                upload_to="catalog/photo",
                verbose_name="Изображение",
            ),
            preserve_default=False,
        ),
    ]
