# Generated by Django 5.1.2 on 2024-10-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_view_counter_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="view_counter",
        ),
    ]
